[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MSD-SOP"
authors = [{name = "Mohsen Pourjam", email = "mohsenpm50@gmail.com"}]
dynamic = ["version", "description"]
